/**
 * Resolve / cache the on-device Whisper ggml model.
 *
 * Prefer order:
 * 1. EXPO_PUBLIC_WHISPER_MODEL absolute path
 * 2. Previously cached file in documentDirectory
 * 3. Bundled Metro asset (after `npm run whisper:fetch` + EAS build)
 * 4. Optional Wi‑Fi download into documentDirectory (for field prep at home)
 */
import { Asset } from "expo-asset";
import Constants from "expo-constants";
import * as FileSystem from "expo-file-system";
import * as Network from "expo-network";

const MODEL_FILE = "ggml-tiny.en.bin";
const MODEL_DIR = `${FileSystem.documentDirectory}models/`;
const MODEL_PATH = `${MODEL_DIR}${MODEL_FILE}`;

/** Official whisper.cpp ggml tiny.en (~75MB) — download only on Wi‑Fi when prep'ing for rural use. */
export const WHISPER_MODEL_URL =
  "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin";

export async function getCachedModelPath(): Promise<string | null> {
  const envPath = process.env.EXPO_PUBLIC_WHISPER_MODEL;
  if (envPath) {
    const info = await FileSystem.getInfoAsync(envPath);
    if (info.exists) return envPath;
  }

  const cached = await FileSystem.getInfoAsync(MODEL_PATH);
  if (cached.exists) return MODEL_PATH;

  const bundled = await tryBundleModelToCache();
  if (bundled) return bundled;

  return null;
}

async function tryBundleModelToCache(): Promise<string | null> {
  const extra = Constants.expoConfig?.extra as
    | { whisperBundled?: boolean }
    | undefined;
  if (!extra?.whisperBundled) return null;

  try {
    // Generated by scripts/fetch-whisper-model.mjs — null module if not fetched.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const mod = require("./whisper-model.generated.js");
    if (!mod) return null;
    const asset = Asset.fromModule(mod);
    await asset.downloadAsync();
    const uri = asset.localUri || asset.uri;
    if (!uri) return null;

    await FileSystem.makeDirectoryAsync(MODEL_DIR, { intermediates: true });
    // If already a file:// path from the bundle, copy into a stable location for whisper.rn.
    if (uri.startsWith("file://") || uri.startsWith("/")) {
      await FileSystem.copyAsync({ from: uri, to: MODEL_PATH });
      return MODEL_PATH;
    }
    const result = await FileSystem.downloadAsync(uri, MODEL_PATH);
    return result.uri;
  } catch (e) {
    console.warn("Bundled Whisper model unavailable:", e);
    return null;
  }
}

export type ModelDownloadProgress = {
  totalBytes: number;
  writtenBytes: number;
  pct: number;
};

/**
 * Download the tiny.en model over Wi‑Fi so rural trips stay offline afterward.
 * Refuses cellular by default (set allowCellular to override).
 */
export async function downloadWhisperModel(opts?: {
  allowCellular?: boolean;
  onProgress?: (p: ModelDownloadProgress) => void;
}): Promise<string> {
  const state = await Network.getNetworkStateAsync();
  if (state.isConnected === false) {
    throw new Error("No network — connect to Wi‑Fi to download the speech model.");
  }
  if (
    !opts?.allowCellular &&
    state.type === Network.NetworkStateType.CELLULAR
  ) {
    throw new Error(
      "Speech model is ~75MB. Connect to Wi‑Fi (or pass allowCellular) before downloading.",
    );
  }

  await FileSystem.makeDirectoryAsync(MODEL_DIR, { intermediates: true });
  const callback = opts?.onProgress
    ? (data: { totalBytesWritten: number; totalBytesExpectedToWrite: number }) => {
        const written = data.totalBytesWritten;
        const total = data.totalBytesExpectedToWrite;
        opts.onProgress!({
          writtenBytes: written,
          totalBytes: total,
          pct: total > 0 ? Math.floor((written / total) * 100) : 0,
        });
      }
    : undefined;

  const result = await FileSystem.createDownloadResumable(
    WHISPER_MODEL_URL,
    MODEL_PATH,
    {},
    callback,
  ).downloadAsync();

  if (!result?.uri) throw new Error("Model download failed");
  return result.uri;
}

export async function isWhisperModelReady(): Promise<boolean> {
  return !!(await getCachedModelPath());
}
